language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # LOCAL_TOKEN
    - secure: VpSb+eter4TPpJEBViDfMfWgVGv4l/BYavuMPoMY5TtWVuM9nF9dN1DTMR/1vmMocyofLihOt1BgQT0OZtEdzCVw8iDgUqgstlkhrkUfZ2joQrL9L6dFTiuPZ7Qowyo433OWpfe2Id7chBILqx980VKyo6YuHaEM4X4frcwJBxQtJBCVaE0Zdfr49bOUVzFD5nM4R3/vwJdZERhmtm4muWDds7QDQZ9e1iJj+cnqgIayp41YaU1GzSRwDkFIetVE9TcGyoPPEt7d8hpgLGXalVzMRgL6x+EqXdV+MKBAimcdvbB+FGjMOmxHY6f6FURMiMOUHHEdoGyxSWg/LtRHpX4Wd8iEkF4XT4siB70D8q9ZWFvx01yAGffCK47ED9H+VvFL2jAWuf9JkPXCi0cY5l19mgVHPWjOE3UAoMW36cy1jgcL0kznbnPf6pYuYoC0zI/WYNmfNPHuP8MfZmIlhYc9bU8Kvw3MNkwEbGt6n2afSd2itjC63bemvpInqCc0LpJltAw7+tOhZ2ucu4ti+RdAsoUIUSQuauERLlaa7NcYxfvC6t25LUF4Z8qYhGo3SWLH3H+WKAXk8CS+C1DvvXp0oGB7b8IvK2zHL1OE5LBT1/SnhC4iWZTvOzCjz/PRqfv+HIpytkV7YodJ26R/qD6U/m2g6mfZ9eT6tEChKkQ=

    # LOCAL_SECRET
    - secure: dTqsG9x0Op5NLUd6WpebeuntvJMjVnEysGaBezfkbBeiwaA3beFO8Oo5DnyRRPjIfjGOl2BPanMmD76iPRK6fFmshqorY1UGid0eB2esAzCzkzb+UR0N+Y3gRfc9AdofCJ49GeJDSYpz4WU3IBoAFPZE9qoe9id4/ZIx6htI1FIDPuwMqcTcdkh4n/8iLv0o1LUfjwsfzyJfsTF2pXXOx31kfPgGm6R/B9lZ0/rDTfMBlgGQsh7Q8wsKKzPlG/rODhMyKlr0rQ9OUr5Nr/gGDxSksgbWV6Lu8ce3D6L+VftBEOfSYxJsKqLc/FjXrmrvXZrQBi7HULEnIPPbWSnGbVhmhBT/kKvIJRC+P/429UFRWF365NbHXpAM5YHR/1bIWMabQ/JUNOSiIaK/Q5EskqakUR82JJkHmkXpTIwf22MKGu/DCCsQd0dDwdYWmD1xBllyNUKUWfpzLu7Ym0kEGJjnnPhAh9s70SzIVcUm4tH+EW6Fr4f+E0r21Txt+yD1fTNq4XfeE/a0/B0oBnlVLCv/frZ1dviblpof9QIOp3AkRVgL83t7Y2OUNSvKOBpWIoGPv/aFYP9sJltJPrnZUl8DLGAQFAzOZYHEpNlaCAoCng3uQYqTHZ0qvoEsO2746xbwcL4vhAuuaFDmq9vRPafW9gxAUNwx4B1pAvTkBv4=
