language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # LOCAL_TOKEN
    - secure: r0m/yVes2HS1PCpNf0xd3QfTijAQB7pcB+k6fgtnsnVP0S49mH9YKp42l6gmTXOwYfayGPDbQAxZp6CV5ZUj2fAIx5gba9YJgbqmGNEQKpI+gaAB0OU4cYe9lOxNA9Pom/n6VYqaYDUiskMhIGJNeX9AIrzQikw28QIP2THYjBs4jtZNsi28aLwCQQMeLWiDTGLOJbIUaPguTY5FL22Zm44XJwzOz40g8kwusPeB1hAhFEocqKnJrmn+R8yp/ij/eOHZtLpNjsfdSWEl8lqcHy9crObcGKgbtv955tms+dK34cl8t6gST6n8KJORk+8HckQgtM0EUhvTceiO2u+4b0Pcx/M7l8nCXMwFT5OD6A0uwpSNQ0N6UkDiH9fw8NOUHnRB/Fp5TsRP437Ro5XwKCLuyZ9ahSGrf3exFo4dormkfqcS8vRjPrm45MZN0NdY4o5t5qnUHK+GP5Mm+/9rSkkleU7u4tfL2Tb18vgCHyl8fQnVNcB47+K9fwdmoLXEZHSWAt4lK+0pCyWeWUs923geT4T+q7B10kPyFVHeq2mQjNfAjjp323107Ko7orkVeOjHigTwY//IthIy67eAw0EFID+zL4kptFq3ie7cWeMZfNPAolaVNwL1XbRS0b43zuj18Ga37Cs9MNimDvhSu7yiU/5dQ75WHh/fKGC96Co=

    # LOCAL_SECRET
    - secure: gljwk44LpX5h2leaxIZ7OUnReRVIgUcZUyXSnaJyDaT1mJRnLiBiNHXGNMf6eudyEu6vh2CIlhS/eItZbwVWnMyWkoL4ZFaWWfXxEZWyVSIp0VIfy1DMId9C/JlPA6dNGSpK92tcM2FlnvHu1O4w600bG8ftiZBaFypGN3Cv5o0UB1rryBzlIgifLCvwt7f2NI5xvGq2jSFvAnNEAXSnwiWQeNjxb/2eh8WMDRI+Ip6Z5AiJhF5+QMK9OfJCy0hCyZ8AdqlcoHUoBNohohLpSRbKuLx+PWxGqSFnTjRSVQKdKe1AfP0Nxyzq8PL+D/QfDB3Km/h8HucYLPhGkcN6mB1hrSjr45SlQylsueCoSNOTN1/K73Q33EPrHguGm1XiYoMWpANBQsa1grWQdE14XvqVDGx4FcHTg+z3Nul5RHmev8mQmo9hioTx2HMx8OklWK+euN4dRM9W7Mw2yb897tYG9iHBlB5Gp9coCeqInM2ms26tPZ3SSMJY06u8eLqhFOWw6Vg6wP6kbUxqucuo+bSzh113X0AytIfFOkXHV1887NkNLUYp6/9AWTg/IX0cuz3cRuAL61tHadWHv11f9lkRz48f2gWQgv+PGsO5VrVyEaJWtrjgZ8CaImi3zFQc+FFT5Q4TJlFpEsVjrqZwKCXfxfP5a8LggZMLJuUGCsc=
