language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # LOCAL_TOKEN
    - secure: gZ8aE33CAjstm3Sa/iiqOwGyNsdC6/m0GXR3kQZtBPYJX6Q6F83bhgVrlqlbo+8/hd/mA9cykKtdDCi8UqsAYg/Rm61Lde3ig8flyGAvDNd/bFC3tYlGNcFiYp5mbTMx2Yc4fWEPy7sTOZHXA3KfpHubuxAv2u/caZrvzlGBRRcypWDLYTxjHUozKb9gNdwzvfmV/S6Aw6R/DU+95L9gbcAVZtS4302wJF/V69C+oMXv+lkN8WWXBTbChBpi5bg2TPZ4R3R327q3IF1sjRkWQ7JAYEYuoYm5tL+BpPTr9CNsZmNO/uV6eR/uccFcexO49J9OgW5k9yMfoqGg+F9itiuybOp5XgNBbBQNxS+q10PVZtTXGoJoSONEZWPnsPK9cVpKu0whoQ+aqevHLO7s9lGjDvhCq16YveFOJA0xeFzLmNPfaLS4yE70w1xevVIq5wEs38HAjIcp3Laj8slAzkccCZMGo9GalgDxdPezCygagyPGcWdKtuixrmCpS0nuGrb6Y7uJwQiLfH6CsEB6zmeoReDwEomsNjZEKgiGzeoKLH3vDLcR6rCn7kfXFg6PMyLXZmG9r/4XuZ7AOf+3eOvDf0B5amoM/h3cbCLP31xAQeKugFb5TbDMPr/WcOa3lojE2cV94N/cWBKHQESGCXE8SiDyBiRG5bBLL1GBQVM=

    # LOCAL_SECRET
    - secure: HihGrQCD9WC0iLQIaGUCOyS/SUH91bNKfv4+N5weMoyUDBFycAMcbH7IN5XQptefXCYytYmPpOZTG7tsjpJNzKa/96olxo1cUd6Vybkb2FNDD72GkQaVzS+H8TrMFO/b+b8PfF/fm2jCD866V1GEMnytoJ5nsZoJKCqxl2MIRh6iuMe3dR4a5jvW6ImO5VUjIeD4uvMvYtYUsQVFtFZG49C3/U1YLSsRR3VV2QeA+xS6X2Lon/gnSn+PEs2iXo0ZXWWmWDmKDLicbX/LY3yHE3bhIyQkH1+g/29WHPbPcAA/OPKWAew0CZBG5aTuqqzhzROMqdzGrvP0b/RcEpzVXuIWV4mVY3qV3oN1ZKnXNV+1F7SiEI69Ai0kGqF1TWd8dAOHKJxXpEvAE79zlXjrYHjhVzjbHORCkK9xPq1pIZvGqkLxtEU8ygCunkXZ+U/XPP6sgfVVr1wNnH6z/L8GRAXPFu4k+/yJCIuSeXC1pBjDc3NnFk74rfFA20ylc1XNlop0njDpOkp6VDPr5oH60TIwacYpLllEiPcEKffB/gu9MqN7utPxfrEkkvN7PMQ5j4V5iIeAdh4P6mrIUBSZWCgiELyB+1L+DbbhOzapL9M/fg1oKEgpXN40sQf8uMFMAmEoPgW7K37xYuk9POAxDHRpjwY8Vf626ob6a35peMI=
